#!/usr/bin/env ruby
require 'chat_bot'
require 'auto_marshalling_map'
require 'optparse'
require 'gdbm'

# Parse arguments.
data_file = nil
answer_limit = 1000
OptionParser.new do |opts|
  opts.banner "Usage: #{File.basename(__FILE__)} options"
  opts.separator ""
  opts.separator "Options may be following:"
  opts.on("-d", "--data FILE",
          "Store all data in FILE") do |file|
  	data_file = file
  end
  opts.on("-a", "--anwser-limit LIMIT",
  	    "Limit bot answer to max. LIMIT characters.",
  	    "Default is #{answer_limit}.") do |limit|
  	answer_limit = limit
  end
  opts.on("-h", "--help",
          "Show this message and exit.") do
    puts opts
    exit
  end
end.parse!
abort %(--data is not specified) if storage_file.nil?
# Serve!
begin
  # 
  GDBM.open(data_file) do |data|
    # 
    bot = ChatBot.from(AutoMarshallingMap.new(data))
    # Serve!
    loop do
      # 
      method, uri, version = STDIN.gets.split(/ /+, 3)
      
      # 
      headers = {}; while true
        header = STDIN.gets
        break if header == "\n"
        header = header.split(/\: +/, 2)
        headers[header[0]] = header[1]
      end
      # 
    end
  end
rescue Exception => e
  abort e.message
end